### ISSUE TITLE
Can't deploy modules using the RAD UI

### ISSUE THREAD

**Issue by shiyghannavti** [GoogleCloudPlatform/rad-lab#194]
I am trying to setup the RAD UI after successfully setting up the launcher. I have gone through the documentation multiple times and can't see where I am going wrong, but I consistently get the error message below.

The important message appears to be

    "status": {
      "code": 5,
      "message": "Couldn't read commit "
    }

Not sure if cloud build is having challenges accessing a commit to the git repo?

cf-rl-create-identity@rad-lab-ui-9922.iam.gserviceaccount.com has been assigned the roles/artifactregistry.reader role. I even went to the extreme and granted the basic roles/owner to the rad-lab-ui-9922 project. Artifact Registry is enabled.

{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 5,
      "message": "Couldn't read commit "
    },
    "authenticationInfo": {
      "principalEmail": "cf-rl-create-identity@rad-lab-ui-9922.iam.gserviceaccount.com",
      "serviceAccountDelegationInfo": [
        {
          "firstPartyPrincipal": {
            "principalEmail": "service-492777744572@gcf-admin-robot.iam.gserviceaccount.com"
          }
        }
      ],
      "principalSubject": "serviceAccount:cf-rl-create-identity@rad-lab-ui-9922.iam.gserviceaccount.com"
    },
    "requestMetadata": {
      "callerIp": "2600:1900:2001:2:0:0:1:a01",
      "callerSuppliedUserAgent": "grpc-node-js/1.6.7,gzip(gfe),gzip(gfe)",
      "requestAttributes": {},
      "destinationAttributes": {}
    },
    "serviceName": "cloudbuild.googleapis.com",
    "methodName": "google.devtools.cloudbuild.v1.CloudBuild.RunBuildTrigger",
    "authorizationInfo": [
      {
        "resource": "projects/rad-lab-ui-9922",
        "permission": "cloudbuild.builds.create",
        "granted": true,
        "resourceAttributes": {}
      }
    ],
    "resourceName": "projects/rad-lab-ui-9922/triggers/rad-lab-module-create",
    "request": {
      "projectId": "rad-lab-ui-9922",
      "triggerId": "rad-lab-module-create",
      "source": {
        "substitutions": {
          "_MODULE_NAME": "appmod_project",
          "_DEPLOYMENT_ID": "9dcb"
        }
      },
      "@type": "type.googleapis.com/google.devtools.cloudbuild.v1.RunBuildTriggerRequest"
    }
  },
  "insertId": "95yu1zdjl15",
  "resource": {
    "type": "build",
    "labels": {
      "project_id": "rad-lab-ui-9922",
      "build_trigger_id": "rad-lab-module-create",
      "build_id": ""
    }
  },
  "timestamp": "2023-10-23T12:10:55.702832649Z",
  "severity": "ERROR",
  "logName": "projects/rad-lab-ui-9922/logs/cloudaudit.googleapis.com%2Factivity",
  "receiveTimestamp": "2023-10-23T12:10:55.941105070Z"
}

----

{
  "textPayload": "Error: 5 NOT_FOUND: Couldn't read commit \n    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:189:52)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)\n    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)",
  "insertId": "6536696200004625cbfe3e23",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "project_id": "rad-lab-ui-9922",
      "function_name": "cf-rl-create-module-fe381"
    }
  },
  "timestamp": "2023-10-23T12:38:58.017957Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "46grt7hp9mzu",
    "instance_id": "0037d6d5d34ffbed1a2a6cb3fbd28c91aa72d00fe9e87d258055ca951216a295be7e882d6a0a761ff6fa9083c3909254fa14fb4b50a90997dc2874df16183296dbeed1"
  },
  "logName": "projects/rad-lab-ui-9922/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/rad-lab-ui-9922/traces/a4e5ed27babeeaf8f4b6ceffb2cc14aa",
  "receiveTimestamp": "2023-10-23T12:38:58.315508062Z",
  "errorGroups": [
    {
      "id": "CJ69k8PhgvTNKQ"
    }
  ]
}

**Comment by shiyghannavti** [comment]
This appears to have been caused by the repository being configured for a specific region as opposed to using the global option.
